### ISSUE TITLE
Docker-compose에 InfluxDB 데이터를 호스트 OS와 연결했지만, 데이터가 계속 휘발되는 현상 

### ISSUE THREAD

**Issue by kimsehwan96** [kimsehwan96/influxdb-study-with-python#1]
```yml
version: '3'
#influxdb 컨테이너와 grafana 컨테이너를 쉽게 실행하기 위한 도커 컴포즈 파이
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports: 
      - "8086:8086"
    #데이터가 휘발되지 않게 하기 위해서 로컬에 있는 특정 볼륨과 연동
    #mkdir -p /Users/gimsehwan/docker/influx/data
    volumes:
      - /Users/gimsehwan/docker/influx/data:/var/lib/influxdb
      #내 로컬볼륨 리소스와 influxdb 도커 컨테이너의 볼륨을 연동!

  grafana:
    image: grafana/grafana:7.3.7-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    #데이터가 휘발되지 않게 하기 위해서 로컬에 있는 특정 볼륨과 연동
    #mkdir -p /Users/gimsehwan/grafana/data/data
    volumes:
      - /Users/gimsehwan/docker/grafana/data:/var/lib/grafana
    user: "0"
    links:
      - influxdb

#links를 위 같이 작성하면. influxdb라고 url를 요청하면
#자동으로 influxdb의 내부 ip address와 port를 찾아 들어감 !
```

현재 docker-compose 파일은 다음과 같습니다.

하지만 자료를 찾아본 결과 influxdb 2버전대의 경우 `- /Users/gimsehwan/docker/influx/data:/var/lib/influxdb` 와 같이
컨테이너 볼륨을 `/var/lib/influxdb`로 하는 경우 데이터가 계속 휘발되는 현상이 있다는것을 확인했습니다.

https://community.influxdata.com/t/where-is-the-docker-data-stored/10108/2

해당 이슈를 확인해서 도커 컴포즈 파일 수정이 필요합니다
